export default {
  FETCH_BOOKS_BEGIN: "FETCH_BOOKS_BEGIN",
  FETCH_BOOKS_SUCCESS: "FETCH_BOOKS_SUCCESS",
  FETCH_BOOKS_FAILURE: "FETCH_BOOKS_FAILURE",
  SET_TEXT_FILTER: "SET_TEXT_FILTER",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE"
};
